<?php require 'justbringit/thismarket.php';?>

<!DOCTYPE html>
<html>
    
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <link rel="stylesheet" href="https://2019fun.justmy.com/assets/dev2019/main.css">
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans"/>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Comfortaa"/>
  <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>
  <link rel="shortcut icon" type="image/png" href="https://2019fun.justmy.com/bran-media/favicon_bGd_icon.ico"/>
  <link rel="shortcut icon" type="image/ico" href="https://2019fun.justmy.com/bran-media/favicon.png"/>

<!-- Google / Search Engine Tags -->
<meta itemprop="name" content="Welcome to JustMy: Your LOCAL Hub!">
<meta itemprop="description" content="JustMy is a Hub where LOCALS come together to discover and create. Where people, places, events, and ideas go to #Beamazing. This is JustMy!">
<meta itemprop="image" content="https://2019fun.justmy.com/bran-media/Social_Home.jpg">

<!-- Facebook Meta Tags -->
<meta property="og:type" content="website">
<meta property="og:title" content="Welcome to JustMy: Your LOCAL Hub!">
<meta property="og:description" content="JustMy is a Hub where LOCALS come together to discover and create. Where people, places, events, and ideas go to #Beamazing. This is JustMy!">
<meta property="og:image" content="https://2019fun.justmy.com/bran-media/Social_Home.jpg">

<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Welcome to JustMy: Your LOCAL Hub!">
<meta name="twitter:description" content="JustMy is a Hub where LOCALS come together to discover and create. Where people, places, events, and ideas go to #Beamazing. This is JustMy!">
<meta name="twitter:image" content="https://2019fun.justmy.com/bran-media/Social_Home.jpg">

<!-- Meta Tags Generated by The One and Only JR -->
    
    
    
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://2019fun.justmy.com/assets/dev2019/menu.js" type="text/javascript"></script>
    
    <style type="text/css">
        h1#title1 {
            font-family: 'Roboto';
        }
	h5#card {
            font-family: 'Roboto';
        }

        h4#title2 {
            font-family: "Open Sans";
            font-size: 26px;
        }
        h6#header {
            font-weight: 600;
            color: #666666;
            font-size: 19px;
        }
        p#excerpt {
            line-height: 1.9em;
            color: #666666;
            font-size: 17px;
            font-family: "Open Sans";
            font-weight: 500;
        }
        p#by {
            font-family: "Comfortaa";
            font-size: 28px;
            color: #0a0a0a;
        }
        img#footer {
            border-radius: 10px;
            border-bottom-right-radius: 0px;
            width: 88%;
            height: auto;
        }
        
        h4#footer {
            color: white;
        }
        
        p#footer {
            color: white;
        }
           p#content-header {
            color: #333;
            font-weight: 100;
            font-size: 50px;
        }
        p#body {
            line-height: 1.9em;
            color: #666666;
            font-size: 18px;
            font-family: "Roboto Slab";
        }
	p#cardlink {
	    line-height: 1.9em;
            color: #666666;
            font-size: 14px;
            font-family: "Roboto Slab";

	}
        img#photo {
            border-radius: 8px;
            border-bottom-right-radius: 0px;
            width: 100%;
            height: auto;
        }
        iframe#video {
            border-radius: 8px;
            border-bottom-right-radius: 0px;
            text-align: center;
            box-shadow: 8px 8px 10px #cbcbcb;
        }
        
        p#video span {
            font-size: 16px;
        }
        
        p#video {
            color: #404040;
        }
	img#card {
            width: 100%;
            padding-top: 10%;
            padding-bottom: 10%;
            padding-right: 68%;
        }
    </style>
</head>

<body>

  <!-- MENU START -->
 <?php require 'justbringit/nav.php';?>
  <!-- MENU END -->




 <!–– Part 1  |  Main image, full width.  Home_Page_Spotlight.jpg    with title image over the top  and centered  title_image.png.   A red button with white text "Don't Burn Up the Grill!  Read On!––>
  <div class="section section-hero" style="background-image: url(https://2019fun.justmy.com/bran-media/Home_Page_Summer_Drinks.jpg);">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <img src="https://2019fun.justmy.com/bran-media/title_summer_drinks.png">
          <a href="summer_drinks.php" class="btn btn-xl btn-primary herocta"> Be the Life of the Party</a>
        </div>
      </div>
      </div>
    </div>
  </div>
    
    
    
<!–– Part 2  |  Purple JustMy Logo overhanging from the bottom of the large image.  To the left of the line "MarketName [JustMyMemphis]: Your LOCAL Hub!––>
  <div class="section-subhero">
    <div class="container">
      <div class="subhero">
        <div class="subhero-img">
          <img src="https://2019fun.justmy.com/assets/dev2019/justmy.jpg">
        </div>
        <div class="subhero-txt">
          <p><?=$market['market_site_title']?>: Your LOCAL Hub</p>
        </div>
      </div>
    </div>
  </div>
    
    
    
<!–– Part 3  |  Pardon Our Dust Banner  pardon_dust_section_image.png   !––>
  <div class="section section-content">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 section-content-inside">
          <img id="photo" class="banner" src="https://2019fun.justmy.com/bran-media/pardon_dust_section_image.png">
        </div>
      </div>
    </div>
  </div>
    
    
<!–– Part 4  |  Full width splitscreen on the Left  Slogan_Home.png over text "JustMy is a Hub where LOCALS come together to discover and create. Where people, places, events, and ideas go to #Beamazing. This is JustMy!"     Text should be white with #7F00FF background.  Video should be on the other side:  https://vimeo.com/344461808 !––>
  <div class="section section-split-4">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-6 section-left">
          <img src="https://2019fun.justmy.com/bran-media/Slogan_Home.png">
          <div>JustMy is a Hub where LOCALS come together to discover and create. Where people, places, events, and ideas go to #Beamazing. This is JustMy!</div>
        </div>
        <div class="col-xl-6 section-right">
          <style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; height: auto; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/344461808' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
        </div>
      </div>
    </div>
  </div>

    
    


<!–– Part 5  |  Six features in 2 rows of 3
    1.   summer_drinks.php  |  Summer Drinks  /  it's time to relax and chill!
    2.   this-side-chick-wants-a-commitment.php  |  This 'SIDE CHICK' Wants a Commitment  /  LoveBIG, LiveBIG
    3.   my_lgbt_story.php  |  MY LGBT STORY  /  My Pride Continues
    4.   a_message_to_memphis_and_black_americans.php  |  A Message to Black America  /  from the Headlines
    5.   july_is_national_grilling_month.php  |  Heat Up the Grills  /  July is National Grilling Month!
    6.   karma-is-the-best-revenge.php  |  Karma Is the Best Revenge  /  LoveBIG, LiveBIG
     !––>
  <div class="section section-split-5">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="box-feature">
            <img src="https://2019fun.justmy.com/bran-media/summer_drinks.jpg">
            <div class="box-copy">
              <div>Summer Drinks</div>
              <a href="summer_drinks.php">It's Time to RELAX and CHILL!</a>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="box-feature">
            <img src="https://2019fun.justmy.com/bran-media/this-side-chick-wants-a-commitment.jpg">
            <div class="box-copy">
              <div>LoveBIG, LiveBIG</div>
              <a href="this-side-chick-wants-a-commitment.php">This 'SIDE CHICK' Wants a Commitment</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <div class="box-feature">
            <img src="https://2019fun.justmy.com/bran-media/mylgbt.jpg">
            <div class="box-copy">
              <div>My Pride Continues</div>
              <a href="my_lgbt_story.php">MY LGBT STORY</a>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="box-feature">
            <img src="https://2019fun.justmy.com/bran-media/amessagetoblackamerica1.jpg">
            <div class="box-copy">
              <div>from the Headlines</div>
              <a href="a_message_to_memphis_and_black_americans.php">A Message to Black America</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <div class="box-feature">
            <img src="https://2019fun.justmy.com/bran-media/grilling3.jpg">
            <div class="box-copy">
              <div>July is National Grilling Month!</div>
              <a href="july_is_national_grilling_month.php">Heat Up the Grills</a>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="box-feature">
            <img src="https://2019fun.justmy.com/bran-media/karma-is-the-best-revenge.jpg">
            <div class="box-copy">
              <div>LoveBIG, LiveBIG</div>
              <a href="karma-is-the-best-revenge.php">Karma Is the Best Revenge</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    
    
<!–– Part 6  |  Facebook Banner linking to Market Facebook Page     facebook_section_image.png         !––>
    
  <div class="section section-content">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 section-content-inside">
          <a href="<?=$market['market_facebook']?>" target="_blank"><img id="photo" class="banner" src="https://2019fun.justmy.com/bran-media/facebook_section_image.png"></a>
        </div>
      </div>
    </div>
  </div>
  
  
  
  
  
  <!--    This is the START of section-card    -->
  <div class="section-content section">
    <div class="container">
      <div class="row">
        <div class="col-xs-12" style="width:100%;">
          <div id="card">
            <div class="row">
              <div class="col-md-8"  style="background-image: url(https://2019fun.justmy.com/bran-media/cards_teamGIVING.jpg);
                                              background-size: cover;
                                              border-top-left-radius: 10px;
                                              border-bottom-left-radius: 10px">
              
              </div>
              <div class="col-md-4">
                  <img src="https://2019fun.justmy.com/bran-media/justmy_teamGIVING_grey.png" style="margin-bottom:2rem;max-height:5rem;max-width:100%;">
                  <h1 id="title1">Helping Non-Profits</h1>  
                  <p>This is the place to grow support for your local non-profit organization and to network with other individuals from the Giving Back Community across the US. JustMy is creating a TOOLbox of services to help you do what you do best, serve your Mission.  Join the team and together we will discover, create, and #BeAmazing. This is JustMy!<br><br> 
				<a href="../team_giving_about.php" class="btn btn-info" role="button">Learn More Now!</a>
                  </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--    This is the END of section-card    -->
  
  <!--    This is the START of section-card    -->
  <div class="section-content section">
    <div class="container">
      <div class="row">
        <div class="col-xs-12" style="width:100%;">
          <div id="card-right">
            <div class="row">
              <div class="col-md-4">
                  <img src="https://2019fun.justmy.com/bran-media/funcrew.png" style="margin-bottom:2rem;max-height:5rem;max-width:100%;">
                  <h1 id="title1">#FunCrew Being Amazing</h1>  
                  <p>Did you ever wish that you could make the world a better place, support your community, and promote your craft all at the same time?  Now you can!  Join the #FunCrew of JustMy and use your talent to promote your city and your business at the same time!  Together we can #BeAmazing.<br><br> 
				<a href="../preregistration_content_partners.php" class="btn btn-info" role="button">Learn More Now!</a>
                  </p>
              </div>
              <div class="col-md-8"  style="background-image: url(https://2019fun.justmy.com/bran-media/cards_funcrew.jpg);
                                              background-size: cover;
                                              border-top-right-radius: 10px;
                                              border-bottom-right-radius: 10px">
              
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--    This is the END of section-card    -->
  
  <!--    This is the START of section-card    -->
  <div class="section-content section">
    <div class="container">
      <div class="row">
        <div class="col-xs-12" style="width:100%;">
          <div id="card">
            <div class="row">
              <div class="col-md-8"  style="background-image: url(https://2019fun.justmy.com/bran-media/cards_teamLOCAL.jpg);
                                              background-size: cover;
                                              border-top-left-radius: 10px;
                                              border-bottom-left-radius: 10px">
              
              </div>
              <div class="col-md-4">
                  <img src="https://2019fun.justmy.com/bran-media/justmy_teamLOCAL.png" style="margin-bottom:2rem;max-height:5rem;max-width:100%;">
                  <h1 id="title1">JustMy for Business</h1>  
                  <p>Growing your business gets easier when you don't go at it alone.  JustMy is introducing #TeamLOCAL to connect business owners from around the country to share tips, ideas, and tools that will help your business thrive.  Membership is free and includes a dynamic profile page for your business.  Join the team, share your stories, and together we will #BeAmazing for communities across the US.  This is JustMy!<br><br> 
				<a href="../team_local_about.php" class="btn btn-info" role="button">Learn More Now!</a>
                  </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--    This is the END of section-card    -->
    


  <!--    This is the START of section-like-instagram    -->
  <div class="section-content section">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 section-content-inside">
          <a href="<?=$market['market_instagram']?>" target="_blank"><img id="photo" class="banner" src="https://2019fun.justmy.com/bran-media/instagram_section_image.png"></a>
        </div>
      </div>
    </div>
  </div>
<!--    This is the END of section-like-instagram    -->









  <!--    This is the START of content-footer    -->
  <div class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <img id="footerlogo" src="https://2019fun.justmy.com/bran-media/justmy.png">
        </div>
        <div class="col-md-3">
          <h4 id="footer">#TeamGIVING</h4>
          <p id="footer">JustMy offers help and support for LOCAL Non Profits, Sign up your organization today!</p>
          <a href="../team_giving_about.php" class="btn btn-info" role="button">Learn More Now!</a>
        </div>
        <div class="col-md-3">
          <h4 id="footer">#TeamLOCAL</h4>
          <p id="footer">Are you trying to grow your LOCAL business? JustMy is here to help with support and tools!</p>
          <a href="../team_local_about.php" class="btn btn-info" role="button">Learn More Now!</a>
        </div>
        <div class="col-md-3">
          <h4 id="footer">Looking for Interns</h4>
          <p id="footer">
            Looking for a great internship that allows you to be apart of the best events and groups in town? JustMy is the Place to Be!
          </p>
          <a href="../looking_for_interns.php" class="btn btn-info" role="button">Check it Out!</a>
        </div>
      </div>
    </div>
  </div>
  <!--    This is the END of content-footer    -->
    
    
    </body>